services:
  - type: web
    name: anaglyph-and-friends
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /healthz
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
