import fs from 'node:fs';
const read=(p)=>fs.readFileSync(new URL(p,import.meta.url),'utf8');
const editor=read('./AnaglyphEditor.tsx');const controls=read('./TechniqueControls.tsx');const app=read('./App.tsx');const main=read('./main.tsx');const imageUpload=read('./ImageUpload.tsx');const pairEditor=read('./StereoPairEditor.tsx');const pairRender=read('./stereoPairRender.ts');const phantogram=read('./PhantogramBuilder.tsx');const modelPhantogram=read('./modelPhantogram.ts');const polarized=read('./PolarizedProjection.tsx');const viewMaster=read('./ViewMasterBuilder.tsx');const viewMasterPdf=read('./viewMasterPdf.ts');const feedbackCss=read('./styles/FeedbackFixes.css');
const required=[
 [editor,'downloadEye','eye downloads'],[editor,'requestFullscreen','fullscreen'],[editor,"event.key.toLowerCase()",'keyboard shortcuts'],[editor,'optimiseRRAnaglyph','retinal rivalry'],[editor,'jpegQuality','JPEG quality'],[editor,'randomdot','random-dot'],[editor,'lenticular','lenticular'],[editor,'cardboard','Cardboard'],[editor,'stereoscope','stereoscope'],[editor,'value="__phantogram__"','phantogram in More techniques'],
 [controls,'Build a new random-dot pattern','random-dot rebuild'],[controls,'Download black/white calibration bars','lenticular calibration'],[controls,'Custom repeating pattern','pattern upload'],[controls,'Color rendering','anaglyph color slider'],[controls,'Black text on white','stereoscope light card'],[controls,'White text on black','stereoscope dark card'],
 [app,'ViewMasterBuilder','View-Master workspace'],[app,"type WorkspaceMode = 'studio' | 'viewmaster' | 'polarized'",'polarized top-level workspace'],[app,"studioSurface === 'phantogram'",'embedded phantogram surface'],[app,'sourceModeSwitch','single/pair source switch'],[app,'onOpenInStudio={openInStudio}','View-Master to Studio handoff'],[app,'PolarizedProjection','polarized projection routing'],[app,'sidebarCollapsed','collapsible sidebar'],[main,'scheduleTechniqueAutoApply','automatic discrete setting apply'],[main,'FeedbackFixes.css','feedback polish stylesheet'],
 [imageUpload,'incomingSourceFile','incoming Studio source handoff'],[imageUpload,'onSourceFile?.(file)','outgoing Studio source handoff'],[pairEditor,'Imported Stereo Pair Studio','imported pair studio'],[pairEditor,'Add pair to View-Master','pair to View-Master handoff'],[pairEditor,'Requires source + depth map','pair-mode depth limitations'],[pairRender,'renderStereoPairOutput','local imported-pair renderer'],[pairRender,'renderAnaglyph','imported-pair anaglyph'],[pairRender,'renderLenticular','two-view lenticular renderer'],
 [feedbackCss,'position: sticky','sticky output preview'],[feedbackCss,'repeat(2, minmax(0, 1fr))','equal stereoscope treatment buttons'],[phantogram,'100 mm ruler','phantogram print calibration'],[phantogram,'reverseDepth','phantogram depth reversal'],[phantogram,"sourceMode === 'model'",'phantogram 3D model source mode'],[phantogram,'GLB 2.0, OBJ, and binary/ASCII STL','phantogram model import UI'],[phantogram,'renderModelPhantogram','phantogram model rendering'],[modelPhantogram,'parseModelFile','3D model parser'],[modelPhantogram,"lower.endsWith('.glb')",'GLB model support'],[modelPhantogram,"lower.endsWith('.obj')",'OBJ model support'],[modelPhantogram,"lower.endsWith('.stl')",'STL model support'],[modelPhantogram,'renderEye','independent physical eye projection'],[modelPhantogram,'pngWithDpi','model phantogram physical DPI metadata'],
 [polarized,'Dual-Projector Polarized 3D','polarized projection workspace'],[polarized,"type Polarization = 'linear' | 'circular'",'linear/circular systems'],[polarized,'0° / 90°','linear polarization axes'],[polarized,'Left / Right circular','circular handedness'],[polarized,'Alignment grid','dual-projector alignment grid'],[polarized,'Crosstalk test','polarization leakage test'],[polarized,'Projector A alignment','independent projector A alignment'],[polarized,'Projector B alignment','independent projector B alignment'],[polarized,'brightness','projector brightness matching'],[polarized,'Swap projector eyes','projector eye swap'],
 [viewMaster,'const rotation = scene * SCENE_STEP_DEG + imageRotation','View-Master pair-level rotation'],[viewMaster,"0° · upright at 3/9 o'clock",'View-Master upright reference pair'],[viewMaster,'Download PDF print master','View-Master PDF primary export'],[viewMaster,'Download SVG (secondary)','View-Master SVG secondary export'],[viewMaster,'fill="#fff"','View-Master pure-white cardstock'],[viewMaster,'prototype geometry','View-Master prototype labeling'],[viewMaster,'L + R','View-Master imported-pair scene mode'],[viewMaster,'Open in 3D Studio','View-Master to Studio scene handoff'],[viewMaster,'using imported stereo pair','mixed View-Master source build'],[viewMasterPdf,'PT_PER_MM = 72 / 25.4','View-Master physical PDF scale'],[viewMasterPdf,'/Subtype /Image','View-Master embedded PDF raster images'],[viewMasterPdf,"type: 'application/pdf'",'View-Master PDF output'],[viewMasterPdf,'const rotation = scene * SCENE_STEP_DEG + imageRotation','View-Master PDF pair-level rotation']
];let failed=false;for(const [text,needle,label] of required){if(!text.includes(needle)){console.error(`Missing established feature contract: ${label} (${needle})`);failed=true;}}if(failed)process.exit(1);console.log(`Established feature contract passed (${required.length} checks)`);
